[project]
name = "tgbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.24.0",
    "numpy>=2.4.0",
    "redis>=7.1.0",
    "rich>=14.2.0",
    "tzdata>=2025.3",
]
